version: "3"
services:
  app:
    restart: on-failure
    build: .
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
      - ./docker-compose/database.yml:/app/config/database.yml # Here we go!
      - ./docker-compose/.gitignore:/app/.gitignore # Here we go!
      - ./docker-compose/.ruby-version:/app/.ruby-version # Here we go!
      - ./docker-compose/Gemfile:/app/Gemfile # Here we go!
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres@postgres/api_development
      TEST_DATABASE_URL: postgresql://postgres@postgres/api_test
  postgres:
    image: postgres:13-alpine
    command: ["postgres", "-c", "fsync=false", "-c", "full_page_writes=off"]
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  bundle_cache: